# Generated by Django 6.0.4 on 2026-04-16 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='created_at',
        ),
    ]
