# Generated by Django 6.0.4 on 2026-04-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_studentdetails_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signup',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
